name: WMS Java CI with Maven 游

on:
  push:
    branches: [ "dev", "main" ] # Se ejecuta cuando subes c칩digo a dev o main
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # Usamos una m치quina Linux de GitHub

    steps:
      # 1. Bajar tu c칩digo
      - uses: actions/checkout@v4

      # 2. Instalar Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 3. Dar permisos de ejecuci칩n al wrapper (por si acaso)
      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      # 4. Correr los Tests y Compilar
      # Nota: Maven en la nube descargar치 todo fresco (sin cach칠 corrupta)
      - name: Build with Maven
        run: ./mvnw clean verify